# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import os, platform, multiprocessing

def memory():
    with open('/proc/meminfo','r') as mem:
        ret = {}
        tmp = 0
        for i in mem:
            sline = i.split()
            if str(sline[0]) == 'MemTotal:':
                ret['total'] = int(sline[1])
            elif str(sline[0]) in ('MemFree:', 'Buffers:', 'Cached:'):
                tmp += int(sline[1])
        ret['free'] = tmp
        ret['used'] = int(ret['total']) - int(ret['free'])
    return round(int(ret['total']/1024)/1000)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(552,271)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 551, 271))
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formFrame = QtWidgets.QFrame(self.tab)
        self.formFrame.setGeometry(QtCore.QRect(40, 40, 181, 101))
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setObjectName("formLayout")
        self.r_sim = QtWidgets.QRadioButton(self.formFrame)
        self.r_sim.setObjectName("r_sim")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.r_sim)
        self.r_sinan = QtWidgets.QRadioButton(self.formFrame)
        self.r_sinan.setObjectName("r_sinan")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.r_sinan)
        self.r_sinasc = QtWidgets.QRadioButton(self.formFrame)
        self.r_sinasc.setObjectName("r_sinasc")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.r_sinasc)
        self.formFrame_2 = QtWidgets.QFrame(self.tab)
        self.formFrame_2.setGeometry(QtCore.QRect(360, 40, 181, 101))
        self.formFrame_2.setObjectName("formFrame_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formFrame_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.gerar_csv = QtWidgets.QPushButton(self.formFrame_2)
        self.gerar_csv.setShortcut("")
        self.gerar_csv.setObjectName("gerar_csv")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.gerar_csv)
        self.baixar_dbc = QtWidgets.QPushButton(self.formFrame_2)
        self.baixar_dbc.setObjectName("baixar_dbc")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.baixar_dbc)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(40, 190, 471, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.start_spark = QtWidgets.QPushButton(self.tab_2)
        self.start_spark.setGeometry(QtCore.QRect(20, 20, 158, 25))
        self.start_spark.setObjectName("start_spark")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 70, 211, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.set_processor = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.set_processor.setWrapping(False)
        self.set_processor.setMinimum(1)
        self.set_processor.setMaximum(multiprocessing.cpu_count())
        self.set_processor.setProperty("value", 1)
        self.set_processor.setObjectName("set_processor")
        self.gridLayout.addWidget(self.set_processor, 0, 1, 1, 1)
        self.n_processador = QtWidgets.QLabel(self.gridLayoutWidget)
        self.n_processador.setObjectName("n_processador")
        self.gridLayout.addWidget(self.n_processador, 0, 0, 1, 1)
        self.n_memoria = QtWidgets.QLabel(self.gridLayoutWidget)
        self.n_memoria.setObjectName("n_memoria")
        self.gridLayout.addWidget(self.n_memoria, 1, 0, 1, 1)
        self.set_memory = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.set_memory.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.set_memory.setMinimum(1)
        self.set_memory.setMaximum(memory())
        self.set_memory.setSingleStep(1)
        self.set_memory.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.set_memory.setProperty("value", 1)
        self.set_memory.setObjectName("set_memory")
        self.gridLayout.addWidget(self.set_memory, 1, 1, 1, 1)

        fsm = QtWidgets.QFileSystemModel()
        if platform.system().lower() == 'linux':
            try:
                index = fsm.setRootPath(os.path.expanduser('~/Documentos/files_csv/'))
            except:
                index = fsm.setRootPath(os.path.expanduser('~/Documentos/'))
        elif platform.system().lower() == 'windows':
            try:
                index = fsm.setRootPath(os.path.expanduser('~\\Meus Documentos\\files_csv\\'))
            except:
                index = fsm.setRootPath(os.path.expanduser('~\\Meus Documentos\\'))

        self.select_data = QtWidgets.QComboBox(self.tab_2)
        self.select_data.setGeometry(QtCore.QRect(370, 20, 141, 25))
        self.select_data.setEditable(False)
        self.select_data.setObjectName("select_data")
        self.select_data.addItem("")
        self.select_data.setModel(fsm)
        self.select_data.setRootModelIndex(index)

        self.read_data = QtWidgets.QPushButton(self.tab_2)
        self.read_data.setGeometry(QtCore.QRect(370, 200, 141, 25))
        self.read_data.setObjectName("read_data")
        self.label_temp = QtWidgets.QLabel(self.tab_2)
        self.label_temp.setGeometry(QtCore.QRect(370, 80, 151, 61))
        self.label_temp.setObjectName("label_temp")
        self.data_temp = QtWidgets.QSlider(self.tab_2)
        self.data_temp.setGeometry(QtCore.QRect(370, 120, 141, 31))
        self.data_temp.setMouseTracking(False)
        self.data_temp.setTabletTracking(False)
        self.data_temp.setAcceptDrops(False)
        self.data_temp.setMinimum(2010)
        self.data_temp.setMaximum(2017)
        self.data_temp.setPageStep(1)
        self.data_temp.setProperty("value", 2010)
        self.data_temp.setOrientation(QtCore.Qt.Horizontal)
        self.data_temp.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.data_temp.setTickInterval(16)
        self.data_temp.setObjectName("data_temp")
        self.range_init = QtWidgets.QLabel(self.tab_2)
        self.range_init.setGeometry(QtCore.QRect(350, 150, 54, 17))
        self.range_init.setObjectName("range_init")
        self.range_end = QtWidgets.QLabel(self.tab_2)
        self.range_end.setGeometry(QtCore.QRect(510, 150, 54, 17))
        self.range_end.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.range_end.setObjectName("range_end")
        self.range_init_2 = QtWidgets.QLabel(self.tab_2)
        self.range_init_2.setGeometry(QtCore.QRect(470, 150, 54, 17))
        self.range_init_2.setObjectName("range_init_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.n_processador.setBuddy(self.set_processor)
        self.n_memoria.setBuddy(self.set_memory)
        self.range_end.setBuddy(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.data_temp.valueChanged['int'].connect(self.range_end.setNum)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GUIpydbSus"))
        self.r_sim.setText(_translate("Dialog", "SIM"))
        self.r_sinan.setText(_translate("Dialog", "SINAN"))
        self.r_sinasc.setText(_translate("Dialog", "SINASC"))
        self.gerar_csv.setText(_translate("Dialog", "Generate csv"))
        self.baixar_dbc.setText(_translate("Dialog", "Download dbc"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Functions"))
        self.start_spark.setText(_translate("Dialog", "Start Spark"))
        self.n_processador.setText(_translate("Dialog", " Set n. processors"))
        self.n_memoria.setText(_translate("Dialog", " Set memory in GB:"))
        self.select_data.setCurrentText(_translate("Dialog", "Select Data"))
        self.select_data.setItemText(0, _translate("Dialog", "Select Data"))
        self.read_data.setText(_translate("Dialog", "Read Data"))
        self.label_temp.setText(_translate("Dialog", " Select range data time"))
        self.range_init.setText(_translate("Dialog", "2010"))
        self.range_end.setText(_translate("Dialog", "2010"))
        self.range_init_2.setText(_translate("Dialog", "2010 -"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Spark"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Manipulate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Preview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Export"))
